### ISSUE TITLE
Too many fibers in tracts/*.json

### ISSUE THREAD

**Issue by soichih** [brainlife/app-wmaSeg#1]
Similar to https://github.com/brain-life/app-AFQ_no-life/issues/1

This app generates too many fibers than most web browsers can handle - although not as extreme as app-AFQ_non-Life.

**Comment by DanNBullock** [comment]
What is the difference between these apps?  Also, I would argue that this
isn't a problem with the app itself, but with the visualizer.  If we need
to down-sample the visualizer, so be it.  Insofar as the actual
identification of streamlines as members of anatomical tracts are
concerned, I suspect the app is behaving as intended.

**Comment by soichih** [comment]
The algorithm used to segment is different - it also uses Freesufer output where AFQ one doesn't. I think both app should have better description / README content to detail the difference.

Yes, tracts/*.json is only used for visualization, and we should sub sample it. We had to do a similar sub sampling for app-life's tracts output (https://github.com/brain-life/app-life/blob/master/main.m#L57). @kitchell What do you think?

**Comment by kitchell** [comment]
We will have to subsample this carefully. Some tracts have a lot and can be probably reduced 50% and still look right but other only have a few streamlines so reducing by 50% would make the tract look weird. Same with AFQ no life.

**Comment by soichih** [comment]
How about.. instead of sub-sampling, we grab the first N fibers for each tract? If there are less than N fibers, we just show all of them for that tract?

I think N = 1000 is probably a good number, but we adjust it.

**Comment by francopestilli** [comment]
As long as it is robust tracts having less than 1000 fibers...

**Comment by kitchell** [comment]
Ok yeah something like that could work. I'll take a look at it. Remind me if I don't do it by a few days from now.

**Comment by soichih** [comment]
@kitchell Reminding you with this update. I still think using first 1000 fibers / track is worth trying.

**Comment by kitchell** [comment]
hi soichi, I went to finally make this change, but realized that one of my visualization apps uses  the tracts.json file to make the images. If we subsample for this file, then down the line we cannot use this file for anything else. Is there any way to subsample right before visualizing in the browser?

**Comment by soichih** [comment]
@kitchell That's too bad. Can you make your visualization app to load tracts from output.mat instead? You should be able to load it via any HDF5 parser..

Or, if it won't do, can you make it to output `tracts/N.sample.json` or something like that for each tract? You can output both the original and sub-sampled tracts? I will update the tractviewer to load sub-sampled tracts if it's available.

**Comment by soichih** [comment]
I've made the update to randomly sample up to 1000 fibers for each tract. I haven't had my browser crash on the newly generated data, but max fiber counts could be tweaked (I think 1000 looks ok?) Closing this issue for now.
