### ISSUE TITLE
Undefined function or variable 'wma_wrapperDev'.

### ISSUE THREAD

**Issue by soichih** [brainlife/app-wmaSeg#3]
I am seeing this on master

```
Undefined function or variable 'wma_wrapperDev'.

Error in main (line 35)

MATLAB:UndefinedFunction
```

**Comment by kitchell** [comment]
See the addpaths I have in the main.m file. you should not use the brlife git/wma repo

**Comment by soichih** [comment]
OK I see. I will update the compile.sh to use the alternative version.
